const ADMIN='1111';
const PLANS=['月4回プラン','月8回プラン','通い放題プラン','ファミリー月4回プラン','ファミリー月8回プラン','ファミリー通い放題プラン'];
const HOL=['2026-01-01','2026-01-12','2026-02-11','2026-02-23','2026-03-20','2026-04-29','2026-05-03','2026-05-04','2026-05-05','2026-05-06','2026-07-20','2026-08-11','2026-09-21','2026-09-22','2026-09-23','2026-10-12','2026-11-03','2026-11-23'];
const USE_MINUTES=40;
const FIXED_SLOT_STEP_MINUTES=50;
const FLEXIBLE_SLOT_STEP_MINUTES=10;
const BLOCK_MINUTES=50;
const FIXED_SLOT_START_MINUTE=490;
const FIXED_SLOT_END_MINUTE=1320;
const FLEXIBLE_NIGHT_START_MINUTE=1320;
const FLEXIBLE_MORNING_END_MINUTE=480;
const db = window.supabase.createClient(window.FRIENDS_SUPABASE_URL, window.FRIENDS_SUPABASE_ANON_KEY);

let adminPass='';
let adminWeek=0,adminDay=0,selectedAdminSlot=null;
let snap={members:[],reservations:[],closed_slots:[],external_blocks:[],purchases:[],purchase_enabled:true};

const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const pad=n=>String(n).padStart(2,'0');
const dk=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const fmtMin=m=>{m=Number(m);return m===1440?'24:00':pad(Math.floor(m/60))+':'+pad(m%60)};
const jp=s=>{let d=new Date(s+'T00:00:00'),w='日月火水木金土'[d.getDay()];return `${d.getMonth()+1}/${d.getDate()}（${w}）`};
const slotRange=m=>`${fmtMin(m)}〜${fmtMin(Number(m)+USE_MINUTES)}`;
const full=(d,m)=>`${jp(d)} ${slotRange(m)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const labelOrEmpty=s=>String(s||'').trim()||'未入力';
const toast=msg=>{if(window.adminSoftToast)window.adminSoftToast(msg);};

async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw new Error(error.message);if(!data?.ok)throw new Error(data?.error||'RPC失敗');return data}
function member(id){return snap.members.find(m=>m.id===id)}
function flexibleStartArr(){let a=[];for(let m=FLEXIBLE_NIGHT_START_MINUTE;m+USE_MINUTES<=1440;m+=FLEXIBLE_SLOT_STEP_MINUTES)a.push(m);for(let m=0;m+USE_MINUTES<=FLEXIBLE_MORNING_END_MINUTE;m+=FLEXIBLE_SLOT_STEP_MINUTES)a.push(m);return a}
function fixedStartArr(){let a=[];for(let m=FIXED_SLOT_START_MINUTE;m<FIXED_SLOT_END_MINUTE;m+=FIXED_SLOT_STEP_MINUTES)a.push(m);return a}
function startArr(){return flexibleStartArr().concat(fixedStartArr())}
function holiday(d){return HOL.includes(d)}
function blocks(d){let day=new Date(d+'T00:00:00').getDay();if(holiday(d))return[[510,820]];if(day===1)return[[510,610],[1080,1330]];if(day===2)return[[510,610],[720,820],[1080,1330]];if(day===3)return[[1080,1330]];if(day===4)return[[690,790],[1215,1315]];if(day===5)return[[1080,1330]];if(day===6||day===0)return[[460,820]];return[]}
function conflict(d,m){let a=Number(m),b=a+BLOCK_MINUTES;return blocks(d).some(([s,e])=>a<e&&s<b)}
function sameBlock(a,b){a=Number(a);b=Number(b);return a<b+BLOCK_MINUTES&&b<a+BLOCK_MINUTES}
function overlapsRange(aStart,aEnd,bStart,bEnd){return Number(aStart)<Number(bEnd)&&Number(bStart)<Number(aEnd)}
function hasReservation(d,m){return snap.reservations.some(r=>r.date===d&&sameBlock(m,r.start_minute))}
function reservationAt(d,m){let list=snap.reservations.filter(r=>r.date===d),exact=list.find(r=>Number(r.start_minute)===Number(m));return exact||list.find(r=>sameBlock(m,r.start_minute))}
function isClosed(d,m){return snap.closed_slots.some(c=>c.date===d&&sameBlock(m,c.start_minute))}
function closedAt(d,m){let list=snap.closed_slots.filter(c=>c.date===d),exact=list.find(c=>Number(c.start_minute)===Number(m));return exact||list.find(c=>sameBlock(m,c.start_minute))}
function externalBlockAt(d,m){let s=Number(m),e=s+BLOCK_MINUTES;return (snap.external_blocks||[]).find(x=>x.date===d&&overlapsRange(s,e,x.start_minute,x.end_minute))}
function hasExternalBlock(d,m){return !!externalBlockAt(d,m)}
function validManualSlot(d,m){return d&&!conflict(d,m)&&!hasReservation(d,m)&&!isClosed(d,m)&&!hasExternalBlock(d,m)}
function weekStart(){let d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+adminWeek*7);return d}
function selectedDate(){let d=weekStart();d.setDate(d.getDate()+adminDay);return d}
function purchaseNeedsAction(r){return r.billing_status!=='completed'}

async function loadSnapshot(){snap=await rpc('fs_admin_snapshot',{p_admin_password:adminPass});window.snap=snap;renderAll()}
window.loadSnapshot=loadSnapshot;
function renderAll(){renderSummary();renderCalendar();renderPurchases();renderMembers();renderClosed();fillTime();renderBadges()}
function renderBadges(){let n=snap.purchases.filter(purchaseNeedsAction).length,b=$('#purchaseBadge');if(b){b.textContent=n;b.classList.toggle('show',n>0)}}
function reservationCard(r){return `<article class='res'><h3>${esc(full(r.date,r.start_minute))}</h3><p>${esc(r.member_name)} / ${esc(r.plan)} / ${esc(r.people)}</p><div class='two'><button class='ghost' data-detail='${esc(r.member_id)}'>会員を開く</button><button class='danger' data-cancel='${esc(r.id)}'>キャンセル</button></div></article>`}
function externalRange(x){return `${jp(x.date)} ${fmtMin(x.start_minute)}〜${fmtMin(x.end_minute)}`}
function externalBlockCard(x){return `<article class='res yoga-private'><h3>ヨガ個別予約：${esc(labelOrEmpty(x.member_name))}</h3><p>${esc(externalRange(x))}</p><p>インストラクター：${esc(labelOrEmpty(x.instructor_name))}</p><p>メモ：${esc(labelOrEmpty(x.note))}</p><button class='danger' data-yoga-delete='${esc(x.id)}'>削除</button></article>`}
function externalSlotRow(x){return `<article class='slot-row closed yoga-private'><div class='time'>${fmtMin(x.start_minute)}〜${fmtMin(x.end_minute)}</div><div><span class='pill closed'>ヨガ個別予約</span> ${esc(labelOrEmpty(x.member_name))}${x.note?` / ${esc(x.note)}`:''}</div><button class='danger' data-yoga-delete='${esc(x.id)}'>削除</button></article>`}
function flexibleSortValue(m){m=Number(m);return m>=FLEXIBLE_NIGHT_START_MINUTE?m:1440+m}
function isFlexibleStart(m){m=Number(m);return (m>=FLEXIBLE_NIGHT_START_MINUTE&&m+USE_MINUTES<=1440)||(m>=0&&m+USE_MINUTES<=FLEXIBLE_MORNING_END_MINUTE)}
function flexibleItemTime(m){return slotRange(m)}
function purchaseCard(r){let done=r.billing_status==='completed';let cls=done?'res done':'res important';return `<article class='${cls}'><h3>${done?'課金対応済み':'追加枠購入'}</h3><p><strong>${esc(r.member_name)}</strong></p><p>購入日時：${new Date(r.created_at).toLocaleString('ja-JP')}</p><p>金額：${Number(r.price||3000).toLocaleString()}円 / 付与枠：${r.slots||1}枠</p><div class='two'><button class='ghost' data-detail='${esc(r.member_id)}'>会員を開く</button>${done?'<span></span>':`<button class='ok' data-billing-complete='${esc(r.id)}'>即時課金対応済みにする</button>`}</div></article>`}
function renderSummary(){let today=dk(new Date()),todayRes=snap.reservations.filter(r=>r.date===today),needs=snap.purchases.filter(purchaseNeedsAction),todayYoga=(snap.external_blocks||[]).filter(x=>x.date===today);$('#summary').innerHTML=`<article class='res metric'><p>会員数</p><strong>${snap.members.length}</strong></article><article class='res metric'><p>予約数</p><strong>${snap.reservations.length}</strong></article><article class='res metric'><p>今日の予約</p><strong>${todayRes.length}</strong></article><article class='res metric'><p>ヨガ個別予約</p><strong>${todayYoga.length}</strong></article><article class='res metric'><p>購入通知</p><strong>${needs.length}</strong></article>`;$('#billingAlerts').innerHTML=needs.length?needs.map(purchaseCard).join(''):'<article class="res done"><p>未対応の購入通知はありません。</p></article>';$('#todayReservations').innerHTML=todayRes.length?todayRes.sort((a,b)=>a.start_minute-b.start_minute).map(reservationCard).join(''):'<article class="res"><p>今日の予約はありません。</p></article>'}
function slotRow(date,m){let r=reservationAt(date,m),c=closedAt(date,m),x=externalBlockAt(date,m);if(r)return `<article class='slot-row reserved'><div class='time'>${slotRange(m)}</div><div><span class='pill reserve'>予約</span> ${esc(r.member_name)} / ${esc(r.people)}</div><button class='danger' data-cancel='${esc(r.id)}'>キャンセル</button></article>`;if(c)return `<article class='slot-row closed'><div class='time'>${slotRange(m)}</div><div><span class='pill closed'>利用不可</span> ${esc(c.reason||'理由なし')}</div><button class='danger' data-open='${esc(c.id)}'>解除</button></article>`;if(x)return externalSlotRow(x);return `<article class='slot-row open' data-slot-action='${date}_${m}'><div class='time'>${slotRange(m)}</div><div><span class='pill open'>空き</span> タップして予約登録／枠止め</div><span>操作</span></article>`}
function renderAdminFlexible(date){let starts=flexibleStartArr(),opts=starts.filter(m=>validManualSlot(date,m)),reserved=snap.reservations.filter(r=>r.date===date&&isFlexibleStart(r.start_minute)).sort((a,b)=>flexibleSortValue(a.start_minute)-flexibleSortValue(b.start_minute)),closed=snap.closed_slots.filter(c=>c.date===date&&isFlexibleStart(c.start_minute)).sort((a,b)=>flexibleSortValue(a.start_minute)-flexibleSortValue(b.start_minute)),external=(snap.external_blocks||[]).filter(x=>x.date===date&&isFlexibleStart(x.start_minute)).sort((a,b)=>flexibleSortValue(a.start_minute)-flexibleSortValue(b.start_minute)),unavailable=starts.filter(m=>conflict(date,m)||hasReservation(date,m)||isClosed(date,m)||hasExternalBlock(date,m)).length;return `<section class='flex-reserve admin-flex'><p class='eyebrow'>深夜・早朝の自由枠</p><h3>予約済み</h3><div class='list'>${reserved.length?reserved.map(r=>`<article class='slot-row reserved'><div class='time'>${flexibleItemTime(r.start_minute)}</div><div><span class='pill reserve'>予約済み</span> ${esc(r.member_name)} / ${esc(r.people)}</div><button class='danger' data-cancel='${esc(r.id)}'>キャンセル</button></article>`).join(''):'<article class="res"><p class="small">予約済みの自由枠はありません。</p></article>'}</div><h3>利用不可</h3><div class='list'>${closed.length?closed.map(c=>`<article class='slot-row closed'><div class='time'>${flexibleItemTime(c.start_minute)}</div><div><span class='pill closed'>利用不可</span> ${esc(c.reason||'理由なし')}</div><button class='danger' data-open='${esc(c.id)}'>解除</button></article>`).join(''):'<article class="res"><p class="small">利用不可にした自由枠はありません。</p></article>'}</div><h3>ヨガ個別予約</h3><div class='list'>${external.length?external.map(externalSlotRow).join(''):'<article class="res"><p class="small">ヨガ個別予約の自由枠ブロックはありません。</p></article>'}</div><h3>新しく操作</h3><div class='row'><select id='adminFlexStart' ${opts.length?'':'disabled'}>${opts.length?opts.map(m=>`<option value='${m}'>${slotRange(m)}</option>`).join(''):'<option value="">操作できる時間がありません</option>'}</select><button class='btn' data-admin-flex-action ${opts.length?'':'disabled'}>会員予約を入れる / 利用不可にする</button></div><p class='small'>10分単位の開始候補はプルダウンにまとめています（予約・利用不可などで選べない候補：${unavailable}件）。重なり判定は50分ブロックです。</p></section>`}
function renderCalendar(){let s=weekStart(),e=new Date(s);e.setDate(s.getDate()+6);$('#weekLabel').textContent=`${jp(dk(s))} 〜 ${jp(dk(e))}`;$('#days').innerHTML=Array.from({length:7},(_,i)=>{let d=new Date(s);d.setDate(s.getDate()+i);return `<button class='day ${i===adminDay?'active':''}' data-day='${i}'><strong>${d.getMonth()+1}/${d.getDate()}</strong><span>${'日月火水木金土'[d.getDay()]}</span></button>`}).join('');let date=dk(selectedDate()),fixed=fixedStartArr().filter(m=>!conflict(date,m)).map(m=>slotRow(date,m)).join('');$('#calendarList').innerHTML=renderAdminFlexible(date)+`<h3 class='slot-section-title'>8:00以降の固定枠</h3>${fixed||'<article class="res"><p>表示できる固定枠はありません。</p></article>'}`}
function renderPurchases(){let list=[...snap.purchases].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));$('#requests').innerHTML=list.length?list.map(purchaseCard).join(''):'<article class="res"><p>購入履歴はありません。</p></article>'}
function renderMembers(){$('#members').innerHTML=snap.members.map(m=>`<article class='res' data-member-card='${esc(m.id)}'><h3>${esc(m.name)}</h3><p>${esc(m.member_code)} / ${esc(m.plan)} / PIN:${esc(m.pin)}</p><p>${esc(m.email||'メール未登録')}</p><div class='two'><button class='ghost' data-detail='${esc(m.id)}'>会員を開く・編集</button><button class='btn' data-copy-login='${esc(m.id)}'>LINE文面コピー</button></div></article>`).join('')}
function renderClosed(){let closed=snap.closed_slots.length?snap.closed_slots.map(x=>`<article class='res'><h3>${esc(full(x.date,x.start_minute))}</h3><p>${esc(x.reason||'理由なし')}</p><button class='danger' data-open='${esc(x.id)}'>解除</button></article>`).join(''):'<article class="res"><p>利用不可枠はありません。</p></article>';let yoga=(snap.external_blocks||[]).length?`<h3>ヨガ個別予約</h3>${snap.external_blocks.map(externalBlockCard).join('')}`:'<h3>ヨガ個別予約</h3><article class="res"><p>ヨガ個別予約はありません。</p></article>';$('#closed').innerHTML=closed+yoga}
function fillTime(){let date=$('#addClosed input[type=date]')?.value,s=$('#addClosed select');if(!s)return;if(!date){s.innerHTML='<option value="">日付を先に選択</option>';return}let opts=startArr().filter(m=>validManualSlot(date,m));s.innerHTML=opts.length?opts.map(m=>`<option value='${m}'>${slotRange(m)}</option>`).join(''):'<option value="">設定できる枠がありません</option>'}
function switchTab(name){$$('.tab[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['dashboard','calendar','customers','requests','settings'].forEach(t=>$('#'+t+'Tab').classList.toggle('hidden',t!==name));if(name==='calendar')renderCalendar();if(name==='settings')fillTime()}
function openDetail(id){let m=member(id);if(!m)return;switchTab('customers');$$('[data-member-detail]').forEach(el=>el.remove());let card=$$('[data-member-card]').find(el=>el.dataset.memberCard===id);if(!card)return;let active=snap.reservations.filter(r=>r.member_id===id).sort((a,b)=>(String(a.date)+String(a.start_minute).padStart(4,'0')).localeCompare(String(b.date)+String(b.start_minute).padStart(4,'0')));let planOptions=PLANS.map(p=>`<option ${m.plan===p?'selected':''}>${p}</option>`).join('');let detail=document.createElement('article');detail.className='res';detail.dataset.memberDetail=id;detail.innerHTML=`<p class='eyebrow'>会員詳細</p><h2>${esc(m.name)}</h2><form id='editMember' class='mini' data-edit='${esc(id)}'><label>会員名<input name='name' value='${esc(m.name)}' required></label><label>メールアドレス<input name='email' type='email' value='${esc(m.email||'')}'></label><div class='two'><label>会員ID<input value='${esc(m.member_code)}' disabled></label><label>PIN<input name='pin' value='${esc(m.pin)}' required></label></div><label>プラン<select name='plan'>${planOptions}</select></label><div class='two'><button class='btn'>会員情報を保存</button><button class='ghost' type='button' data-close-detail>閉じる</button></div></form><div class='three' style='margin-top:10px'><button class='ok' data-grant='${esc(id)}'>追加枠を1枠付与</button><button class='btn' data-copy-login='${esc(id)}'>LINE文面コピー</button><button class='danger' data-delete-member='${esc(id)}'>会員を削除</button></div><h3>この会員の予約</h3><div class='list'>${active.length?active.map(reservationCard).join(''):'<article class="res"><p>予約はありません。</p></article>'}</div>`;card.insertAdjacentElement('afterend',detail);document.dispatchEvent(new CustomEvent('fs-admin-member-detail-opened',{detail:{memberId:id}}))}
function openAdminSlot(date,start){selectedAdminSlot={date,start:Number(start)};$('#adminSlotTitle').textContent=full(date,Number(start));$('#slotMemberSelect').innerHTML=snap.members.map(m=>`<option value='${esc(m.id)}'>${esc(m.name)} / ${esc(m.plan)}</option>`).join('');$('#adminSlotForm').reset();$('#reserveFields').classList.remove('hidden');$('#closeFields').classList.add('hidden');$('#adminSlotDialog').showModal()}
async function submitAdminSlot(fd){let {date,start}=selectedAdminSlot;if(fd.get('action')==='reserve'){await rpc('fs_admin_create_reservation',{p_admin_password:adminPass,p_member_id:fd.get('memberId'),p_date:date,p_start_minute:start,p_people:String(fd.get('people')||'1')+'名',p_note:fd.get('note')||'管理者が代理予約'})}else{await rpc('fs_admin_close_slot',{p_admin_password:adminPass,p_date:date,p_start_minute:start,p_reason:fd.get('reason')||'管理者設定'})}$('#adminSlotDialog').close();await loadSnapshot();toast('反映しました')}
async function openAdmin(){const input=$('#adminPass').value||sessionStorage.getItem('fs_admin_pass')||'';if(input!==ADMIN){alert('管理者パスコードが違います。');return}adminPass=input;sessionStorage.setItem('fs_admin_pass',adminPass);$('#adminPass').value=adminPass;$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');await loadSnapshot()}

$('#adminOpen').addEventListener('click',()=>openAdmin().catch(e=>alert(e.message)));
$('#slotAction').addEventListener('change',e=>{let reserve=e.target.value==='reserve';$('#reserveFields').classList.toggle('hidden',!reserve);$('#closeFields').classList.toggle('hidden',reserve)});
$('#adminSlotForm').addEventListener('submit',e=>{e.preventDefault();submitAdminSlot(new FormData(e.currentTarget)).catch(err=>alert(err.message))});
$('#addClosed input[type=date]').addEventListener('change',fillTime);
$('#addClosed').addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.currentTarget);rpc('fs_admin_close_slot',{p_admin_password:adminPass,p_date:f.get('date'),p_start_minute:Number(f.get('start')),p_reason:f.get('reason')||''}).then(()=>loadSnapshot()).then(()=>toast('この枠を利用不可にしました')).catch(err=>alert(err.message))});

document.addEventListener('submit',e=>{let form=e.target.closest('#editMember');if(!form)return;e.preventDefault();let id=form.dataset.edit,f=new FormData(form);rpc('fs_admin_update_member',{p_admin_password:adminPass,p_member_id:id,p_name:String(f.get('name')).trim(),p_email:String(f.get('email')||'').trim(),p_pin:String(f.get('pin')).trim(),p_plan:String(f.get('plan')).trim()}).then(()=>loadSnapshot()).then(()=>{openDetail(id);toast('会員情報を保存しました')}).catch(err=>alert(err.message))});

document.addEventListener('click',e=>{let tab=e.target.closest('[data-tab]');if(tab)switchTab(tab.dataset.tab);let day=e.target.closest('[data-day]');if(day){adminDay=Number(day.dataset.day);renderCalendar()}let flex=e.target.closest('[data-admin-flex-action]');if(flex&&!flex.disabled){let sel=$('#adminFlexStart');if(sel&&sel.value)openAdminSlot(dk(selectedDate()),Number(sel.value))}let slot=e.target.closest('[data-slot-action]');if(slot){let [date,start]=slot.dataset.slotAction.split('_');openAdminSlot(date,Number(start))}let d=e.target.closest('[data-detail]');if(d)openDetail(d.dataset.detail);if(e.target.closest('[data-close-detail]'))$$('[data-member-detail]').forEach(el=>el.remove());if(e.target.id==='prevWeek'){adminWeek--;adminDay=0;renderCalendar()}if(e.target.id==='thisWeek'){adminWeek=0;adminDay=0;renderCalendar()}if(e.target.id==='nextWeek'){adminWeek++;adminDay=0;renderCalendar()}if(e.target.classList.contains('close'))e.target.closest('dialog')?.close();let c=e.target.closest('[data-cancel]');if(c){rpc('fs_admin_cancel_reservation',{p_admin_password:adminPass,p_reservation_id:c.dataset.cancel}).then(loadSnapshot).catch(err=>alert(err.message))}let o=e.target.closest('[data-open]');if(o){rpc('fs_admin_open_slot',{p_admin_password:adminPass,p_closed_slot_id:o.dataset.open}).then(loadSnapshot).catch(err=>alert(err.message))}let b=e.target.closest('[data-billing-complete]');if(b){rpc('fs_admin_mark_purchase_billed',{p_admin_password:adminPass,p_purchase_id:b.dataset.billingComplete}).then(loadSnapshot).catch(err=>alert(err.message))}let yd=e.target.closest('[data-yoga-delete]');if(yd&&confirm('このヨガ個別予約を削除しますか？')){rpc('fs_yoga_private_delete',{p_admin_password:adminPass,p_external_block_id:yd.dataset.yogaDelete}).then(loadSnapshot).then(()=>toast('ヨガ個別予約を削除しました')).catch(err=>alert(err.message))}});

window.addEventListener('DOMContentLoaded',()=>{const saved=sessionStorage.getItem('fs_admin_pass');if(saved){$('#adminPass').value=saved;openAdmin().catch(()=>{});}});
