const K='friends-serufu-gh-v2';
const BASE='https://kyoheiehime089-cpu.github.io/blossom-yoga-lp/friends-serufu-member-booking-app/';
const PLANS={'月4回プラン':4,'月8回プラン':8,'ファミリー月4回プラン':4,'ファミリー月8回プラン':8};
const HOL=['2026-01-01','2026-01-12','2026-02-11','2026-02-23','2026-03-20','2026-04-29','2026-05-03','2026-05-04','2026-05-05','2026-05-06','2026-07-20','2026-08-11','2026-09-21','2026-09-22','2026-09-23','2026-10-12','2026-11-03','2026-11-23'];
const D={members:[{id:'FS001',pin:'1234',name:'サンプル会員A',plan:'月4回プラン',extraByMonth:{}},{id:'FS002',pin:'5678',name:'サンプル会員B',plan:'月8回プラン',extraByMonth:{}}],reservations:[],closed:[],purchaseRequests:[],member:null,week:0,day:0};
let S=JSON.parse(localStorage.getItem(K)||'null')||structuredClone(D), selected=null;
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
function save(){localStorage.setItem(K,JSON.stringify(S))}
function pad(n){return String(n).padStart(2,'0')}function dk(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function ym(d=new Date()){return dk(d).slice(0,7)}
function norm(p){if(p==='ファミリープラン'||p==='ファミリー週1（月4回）'||p==='ファミリー週1')return'ファミリー月4回プラン';if(p==='ファミリー週2（月8回）'||p==='ファミリー週2')return'ファミリー月8回プラン';if(p==='通い放題')return'月8回プラン';return p||'月4回プラン'}
function normalize(){S.members=(S.members||[]).map(m=>{m.plan=norm(m.plan);m.extraByMonth=m.extraByMonth||m.extraSlotsByMonth||{};if(!m.migratedExtra&&Number(m.extraSlots||0)>0){m.extraByMonth[ym()]=Number(m.extraByMonth[ym()]||0)+Number(m.extraSlots||0);m.extraSlots=0;m.migratedExtra=true}return m});S.reservations=S.reservations||[];S.closed=S.closed||[];S.purchaseRequests=S.purchaseRequests||[];save()}
function importFromUrl(){let p=new URLSearchParams(location.search),id=p.get('mid'),pin=p.get('pin'),name=p.get('name');if(!id||!pin||!name)return;let m=S.members.find(x=>x.id===id), plan=norm(p.get('plan'));if(m){Object.assign(m,{pin,name,plan,email:p.get('email')||m.email||''})}else{S.members.push({id,pin,name,email:p.get('email')||'',plan,extraByMonth:{}})}S.member=id;save();history.replaceState(null,'',location.pathname)}
function minText(m){m=Number(m);return m===1440?'24:00':pad(Math.floor(m/60))+':'+pad(m%60)}function jp(s){let d=new Date(s+'T00:00:00');return `${d.getMonth()+1}/${d.getDate()}（${'日月火水木金土'[d.getDay()]}）`}function full(d,m){return `${jp(d)} ${minText(m)}〜${minText(m+50)}`}
function mem(){return S.members.find(m=>m.id===S.member)}function extra(m,mo=ym()){return Number((m.extraByMonth||{})[mo]||0)}function quota(m){return (PLANS[norm(m.plan)]||4)+extra(m)}
function start(d,m){let x=new Date(d+'T00:00:00');x.setMinutes(Number(m));return x}function month(s){return s.slice(0,7)}function mine(){return S.reservations.filter(r=>r.memberId===S.member&&!r.cancelled).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))}function future(){return mine().filter(r=>start(r.date,r.start)>new Date())}function thisMonth(){return mine().filter(r=>month(r.date)===ym())}function dayMine(d){return mine().filter(r=>r.date===d)}
function isHoliday(d){return HOL.includes(d)}function blocks(d){let day=new Date(d+'T00:00:00').getDay();if(day===6)return[[490,530],[600,790]];if(day===0||isHoliday(d))return[[540,580],[600,790]];return[[720,760],[1110,1300]]}function conflict(d,m){return blocks(d).some(([s,e])=>m<e&&s<m+50)}function starts(){let a=[],x=490;for(let m=x;m<1440;m+=50)a.push(m);for(let m=x-50;m>=0;m-=50)a.unshift(m);return a.filter(m=>m+50<=1440)}
function bkg(d,m){return S.reservations.find(r=>r.date===d&&Number(r.start)===m&&!r.cancelled)}function cls(d,m){return S.closed.find(r=>r.date===d&&Number(r.start)===m)}function canBook(d,m){return start(d,m)-new Date()>=3600000}function canCancel(r){return start(r.date,r.start)-new Date()>=7200000}function daysFrom(d){let a=new Date(d+'T00:00:00'),b=new Date();b.setHours(0,0,0,0);return Math.floor((a-b)/86400000)}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function login(id,pin){let m=S.members.find(x=>String(x.id).toUpperCase()===String(id).toUpperCase()&&String(x.pin)===String(pin));if(!m)return toast('会員IDまたはログインPINが違います。');S.member=m.id;save();render()}
function render(){let m=mem();if(!m){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');return}m.plan=norm(m.plan);$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');let used=thisMonth().length,q=quota(m);$('#memberName').textContent=m.name;$('#memberPlan').textContent=m.plan;$('#memberQuota').textContent=`月の予約回数：${q}回まで`;$('#extraSlots').textContent=`今月の追加枠：${extra(m)}`;$('#usageText').textContent=`${used} / ${q}`;$('#usageBar').style.width=Math.min(100,Math.round(used/Math.max(1,q)*100))+'%';renderNext();renderUsage();renderDays();renderCalendar();renderMine()}
function renderNext(){let r=future()[0];$('#nextReservation').innerHTML=r?`<h3>${full(r.date,Number(r.start))}</h3><p>利用人数：${esc(r.people)}</p><p>50分枠</p>`:'<p>現在、予約はありません。</p>'}
function renderUsage(){let done=mine().filter(r=>start(r.date,Number(r.start)+50)<=new Date()),last=done.at(-1),tm=done.filter(r=>month(r.date)===ym()).length;$('#usageSummary').innerHTML=`<article class='metric'><p>累計利用</p><strong>${done.length}</strong></article><article class='metric'><p>今月利用済み</p><strong>${tm}</strong></article><article class='metric'><p>直近利用</p><strong>${last?jp(last.date):'-'}</strong></article>`;let ms=[];for(let i=5;i>=0;i--){let d=new Date();d.setMonth(d.getMonth()-i);ms.push(`${d.getFullYear()}-${pad(d.getMonth()+1)}`)}let max=Math.max(1,...ms.map(m=>done.filter(r=>month(r.date)===m).length));$('#usageHistory').innerHTML=ms.map(m=>{let c=done.filter(r=>month(r.date)===m).length;return `<div class='history-row'><span>${m.slice(5)}月</span><div class='history-track'><div class='history-fill' style='width:${Math.round(c/max*100)}%'></div></div><span>${c}回</span></div>`}).join('')}
function weekStart(){let d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+S.week*7);return d}function selectedDate(){let d=weekStart();d.setDate(d.getDate()+S.day);return d}
function renderDays(){let s=weekStart(),e=new Date(s);e.setDate(s.getDate()+6);$('#weekLabel').textContent=`${S.week?'次の週':'今週'}：${jp(dk(s))} 〜 ${jp(dk(e))}`;let h='';for(let i=0;i<7;i++){let d=new Date(s);d.setDate(s.getDate()+i);let key=dk(d);h+=`<button class='day ${i===S.day?'active':''}' data-i='${i}'><strong>${d.getMonth()+1}/${d.getDate()}</strong><span>${key===dk(new Date())?'今日':isHoliday(key)?'祝':'日月火水木金土'[d.getDay()]}</span></button>`}$('#days').innerHTML=h;$('#prevWeek').disabled=S.week<=0;$('#nextWeek').disabled=S.week>=1}
function renderCalendar(){let m=mem(),d=dk(selectedDate()),f=$('#timeFilter').value;let slots=starts().filter(x=>filterHour(x,f)&&!conflict(d,x)).map(x=>slot(m,d,x)).join('');$('#calendar').innerHTML=`<article class='day-card'><div class='day-head'><h3>${jp(d)}</h3><span>${blocks(d).length?'予約可能枠':'-'}</span></div><div class='slots'>${slots}</div></article>`}
function filterHour(m,f){let h=Math.floor(m/60);return f==='all'||(f==='morning'&&h>=5&&h<11)||(f==='day'&&h>=11&&h<17)||(f==='night'&&h>=17&&h<23)||(f==='midnight'&&(h>=23||h<5))}
function slot(m,d,s){let r=bkg(d,s),c=cls(d,s),mineSlot=r?.memberId===m.id,klass='',dis='',st='空きあり';if(mineSlot){klass='mine';st='自分の予約'}else if(c||r){klass='booked';dis='disabled';st='予約不可'}else if(daysFrom(d)<0||daysFrom(d)>=14){klass='closed';dis='disabled';st='受付終了'}else if(!canBook(d,s)){klass='closed';dis='disabled';st='受付終了'}else if(future().length>=2){klass='closed';dis='disabled';st='同時予約上限'}else if(dayMine(d).length>=2){klass='closed';dis='disabled';st='同日上限'}else if(thisMonth().length>=quota(m)){klass='closed';dis='disabled';st='回数上限'}return `<button class='slot ${klass}' ${dis} data-d='${d}' data-s='${s}'><span class='time'>${minText(s)}〜${minText(s+50)}</span><span class='status'>${st}</span></button>`}
function openDialog(d,s){let m=mem();if(!canBook(d,s))return toast('予約受付時間を過ぎています。');if(conflict(d,s)||cls(d,s)||bkg(d,s))return toast('この時間は予約できません。');if(future().length>=2)return toast('同時に確保できる予約は2枠までです。');if(dayMine(d).length>=2)return toast('同日に確保できる予約は2枠までです。');if(thisMonth().length>=quota(m))return toast('今月の予約上限に達しています。');selected={date:d,start:Number(s)};$('#dialogTitle').textContent=full(d,s);$('#dialogSummary').innerHTML=`<p><strong>会員：</strong>${esc(m.name)}</p><p><strong>プラン：</strong>${esc(m.plan)}</p><p><strong>今月の予約：</strong>${thisMonth().length} / ${quota(m)}</p>`;$('#bookingForm').reset();$('#dialog').showModal()}
function createBooking(fd){let m=mem();if(!selected||bkg(selected.date,selected.start))return toast('別の枠を選んでください。');S.reservations.push({id:'r_'+Date.now(),memberId:m.id,memberName:m.name,plan:m.plan,date:selected.date,start:selected.start,people:String(fd.get('people')||'1').trim()+'名',note:fd.get('note')||'',createdAt:new Date().toISOString(),cancelled:false});save();$('#dialog').close();selected=null;render();toast('予約が完了しました。')}
function renderMine(){let a=mine();$('#mine').innerHTML=a.length?a.map(r=>`<article class='res'><h3>${full(r.date,Number(r.start))}</h3><p>利用人数：${esc(r.people)}</p><div class='row'><button class='ghost' data-copy='${full(r.date,Number(r.start))}'>内容をコピー</button><button class='danger' data-cancel='${r.id}' ${canCancel(r)?'':'disabled'}>${canCancel(r)?'キャンセル':'キャンセル不可'}</button></div></article>`).join(''):'<article class="res"><p>現在、予約はありません。</p></article>'}
function cancel(id){let r=S.reservations.find(x=>x.id===id);if(!r||!canCancel(r))return toast('キャンセル受付時間を過ぎています。');if(confirm(full(r.date,Number(r.start))+' の予約をキャンセルしますか？')){r.cancelled=true;r.cancelledAt=new Date().toISOString();save();render();toast('予約をキャンセルしました。')}}
function openPurchase(){$('#purchaseAgree').checked=false;$('#confirmPurchase').disabled=true;$('#purchaseDialog').showModal()}function completePurchase(){let m=mem();if(!$('#purchaseAgree').checked)return toast('同意チェックを入れてください。');m.extraByMonth=m.extraByMonth||{};m.extraByMonth[ym()]=extra(m)+1;S.purchaseRequests.push({id:'p_'+Date.now(),memberId:m.id,memberName:m.name,plan:m.plan,status:'auto_granted',billingStatus:'unconfirmed',createdAt:new Date().toISOString(),price:3000,slots:1,month:ym()});save();$('#purchaseDialog').close();render();$('#purchaseCompleteMessage').textContent=`現在の今月の予約上限は ${quota(m)} 回です。`;$('#purchaseCompleteDialog').showModal()}
document.addEventListener('click',async e=>{let tb=e.target.closest('.tab[data-tab]');if(tb){$$('.tab[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tb.dataset.tab));$('#bookingTab').classList.toggle('hidden',tb.dataset.tab!=='booking');$('#mineTab').classList.toggle('hidden',tb.dataset.tab!=='mine')}let d=e.target.closest('.day');if(d){S.day=Number(d.dataset.i);save();renderDays();renderCalendar()}let sl=e.target.closest('.slot');if(sl&&!sl.disabled)openDialog(sl.dataset.d,Number(sl.dataset.s));let ca=e.target.closest('[data-cancel]');if(ca)cancel(ca.dataset.cancel);let cp=e.target.closest('[data-copy]');if(cp){await navigator.clipboard.writeText(cp.dataset.copy);toast('コピーしました')}if(e.target.id==='buySlot')openPurchase();if(e.target.id==='confirmPurchase')completePurchase();if(e.target.id==='logout'){S.member=null;save();render()}if(e.target.id==='prevWeek'&&!e.target.disabled){S.week=0;S.day=0;save();renderDays();renderCalendar()}if(e.target.id==='thisWeek'){S.week=0;S.day=0;save();renderDays();renderCalendar()}if(e.target.id==='nextWeek'&&!e.target.disabled){S.week=1;S.day=0;save();renderDays();renderCalendar()}if(e.target.id==='closePurchaseComplete')$('#purchaseCompleteDialog').close();if(e.target.classList.contains('close'))e.target.closest('dialog').close();});
$('#purchaseAgree').addEventListener('change',e=>$('#confirmPurchase').disabled=!e.target.checked);
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login($('#memberId').value.trim(),$('#pin').value.trim())});
$('#timeFilter').addEventListener('change',renderCalendar);
$('#bookingForm').addEventListener('submit',e=>{e.preventDefault();createBooking(new FormData(e.currentTarget))});
normalize();importFromUrl();render();