const yogaDb = window.supabase.createClient(window.FRIENDS_SUPABASE_URL, window.FRIENDS_SUPABASE_ANON_KEY);
let yogaPass = sessionStorage.getItem('fs_yoga_private_pass') || '';
let yogaSnap = {reservations: [], closed_slots: [], external_blocks: []};
const USE_MINUTES = 40;
const BLOCK_MINUTES = 50;
const TEN_MINUTES = 10;
const NEAR_CANDIDATE_LIMIT = 5;
const DAILY_CANDIDATE_LIMIT = 5;
const HOLIDAYS = ['2026-01-01','2026-01-12','2026-02-11','2026-02-23','2026-03-20','2026-04-29','2026-05-03','2026-05-04','2026-05-05','2026-05-06','2026-07-20','2026-08-11','2026-09-21','2026-09-22','2026-09-23','2026-10-12','2026-11-03','2026-11-23'];
const PERIODS = [
  {key: 'morning', label: '朝', ranges: [[300, 660]]},
  {key: 'daytime', label: '昼', ranges: [[660, 1020]]},
  {key: 'night', label: '夜', ranges: [[1020, 1320]]},
  {key: 'midnight', label: '深夜', ranges: [[1320, 1440], [0, 300]]},
];
const $ = q => document.querySelector(q);
const pad = n => String(n).padStart(2, '0');
const dk = d => d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate());
const fmtMin = m => {m = Number(m); return m === 1440 ? '24:00' : pad(Math.floor(m / 60)) + ':' + pad(m % 60);};
const jp = s => {const d = new Date(s + 'T00:00:00'); return `${d.getMonth() + 1}/${d.getDate()}（${'日月火水木金土'[d.getDay()]}）`;};
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;'}[m]));
function toast(msg){const el = $('#toast'); el.textContent = msg; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2500);}
function setMessage(msg, ok = false){const el = $('#yogaStatus'); if(!el) return; el.textContent = msg || ''; el.className = msg ? `notice ${ok ? 'ok' : 'danger'}` : 'notice';}
async function rpc(name, args){const {data, error} = await yogaDb.rpc(name, args); if(error) throw new Error(error.message); if(!data?.ok) throw new Error(data?.error || 'RPC失敗'); return data;}
function timeToMinute(value){if(value === '24:00') return 1440; const [h, m] = String(value || '').split(':').map(Number); if(!Number.isFinite(h) || !Number.isFinite(m)) return NaN; return h * 60 + m;}
function validTenMinute(minute){return Number.isInteger(minute) && minute >= 0 && minute <= 1440 && minute % TEN_MINUTES === 0;}
function validateTimes(start, end){return validTenMinute(start) && validTenMinute(end) && start < end && start <= 1430 && end >= 10 && end <= 1440;}
function overlapsRange(aStart, aEnd, bStart, bEnd){return Number(aStart) < Number(bEnd) && Number(bStart) < Number(aEnd);}
function blockEnd(minute){return Number(minute) + BLOCK_MINUTES;}
function rangeLabel(start, end){return `${fmtMin(start)}〜${fmtMin(end)}`;}
function rangeText(block){return `${jp(block.date)} ${rangeLabel(block.start_minute, block.end_minute)}`;}
function labelOrEmpty(value){const text = String(value || '').trim(); return text || '未入力';}
function selectedDateValue(){return $('#yogaForm input[name=date]')?.value || dk(new Date());}
function quickDateValue(){return $('#quickDate')?.value || selectedDateValue();}
function fixedBlocks(date){const day = new Date(date + 'T00:00:00').getDay(); if(HOLIDAYS.includes(date)) return [[510,820,'通常ヨガ/セミパーソナル枠']]; if(day === 1) return [[510,610,'通常ヨガ'],[1080,1330,'セミパーソナル']]; if(day === 2) return [[510,610,'通常ヨガ'],[720,820,'セミパーソナル'],[1080,1330,'セミパーソナル']]; if(day === 3) return [[1080,1330,'セミパーソナル']]; if(day === 4) return [[690,790,'通常ヨガ'],[1215,1315,'セミパーソナル']]; if(day === 5) return [[1080,1330,'セミパーソナル']]; if(day === 6 || day === 0) return [[460,820,'通常ヨガ/セミパーソナル枠']]; return [];}
function reasonClass(reason){if(String(reason).includes('セルフジム')) return 'self'; if(String(reason).includes('利用不可')) return 'closed'; if(String(reason).includes('ヨガ個別')) return 'private'; if(String(reason).includes('通常ヨガ')) return 'regular'; if(String(reason).includes('セミパーソナル')) return 'semi'; return 'other';}
function unavailableBlocks(date){const reservations = (yogaSnap.reservations || []).filter(r => r.date === date).map(r => ({start_minute: Number(r.start_minute), end_minute: blockEnd(r.start_minute), reason: 'セルフジム予約'}));
  const closed = (yogaSnap.closed_slots || []).filter(c => c.date === date).map(c => ({start_minute: Number(c.start_minute), end_minute: blockEnd(c.start_minute), reason: c.reason ? `利用不可枠（${c.reason}）` : '利用不可枠'}));
  const yoga = (yogaSnap.external_blocks || []).filter(b => b.date === date).map(b => ({start_minute: Number(b.start_minute), end_minute: Number(b.end_minute), reason: '既存のヨガ個別予約'}));
  const fixed = fixedBlocks(date).map(([s, e, reason]) => ({start_minute: s, end_minute: e, reason}));
  return [...reservations, ...closed, ...yoga, ...fixed].sort((a, b) => a.start_minute - b.start_minute || a.end_minute - b.end_minute);
}
function availabilityFor(date, start, end){if(!validateTimes(start, end)) return {ok: false, reason: '開始・終了時間は10分単位で、終了を開始より後にしてください。'}; const hit = unavailableBlocks(date).find(b => overlapsRange(start, end, b.start_minute, b.end_minute)); if(hit) return {ok: false, reason: `${hit.reason}と重なっています`, block: hit}; return {ok: true, reason: 'この時間は予約できます'};}
function availability(start, end){return availabilityFor(selectedDateValue(), start, end);}
function timeOptions(start = 0, end = 1430){let html = ''; for(let m = start; m <= end; m += TEN_MINUTES) html += `<option value='${fmtMin(m)}'>${fmtMin(m)}</option>`; return html;}
function fillStartSelect(){const start = $('#yogaStart'); if(!start) return; const current = start.value || '08:10'; start.innerHTML = timeOptions(0, 1430); start.value = current; if(!start.value) start.value = '08:10';}
function fillEndSelectFor(startSelect, endSelect, fallbackMinutes = USE_MINUTES){if(!startSelect || !endSelect) return; const startMinute = timeToMinute(startSelect.value); const current = endSelect.value; const minEnd = validTenMinute(startMinute) ? startMinute + TEN_MINUTES : TEN_MINUTES; endSelect.innerHTML = timeOptions(minEnd, 1440); if(current && timeToMinute(current) > startMinute) endSelect.value = current; if(!endSelect.value) endSelect.value = fmtMin(Math.min(1440, startMinute + fallbackMinutes));}
function fillEndSelect(){const form = $('#yogaForm'); fillEndSelectFor(form?.start, $('#yogaEnd'));}
function fillQuickSelects(){const start = $('#quickStart'); if(!start) return; const current = start.value || '08:10'; start.innerHTML = timeOptions(0, 1430); start.value = current; if(!start.value) start.value = '08:10'; fillEndSelectFor(start, $('#quickEnd'));}
function candidateStarts(date, duration = USE_MINUTES){const safeDuration = validTenMinute(duration) && duration > 0 ? duration : USE_MINUTES; const candidates = []; for(let start = 0; start + safeDuration <= 1440; start += TEN_MINUTES){const end = start + safeDuration; if(availabilityFor(date, start, end).ok) candidates.push({date, start, end});} return candidates;}
function nearestCandidates(date, requestedStart, requestedEnd, limit = NEAR_CANDIDATE_LIMIT){const duration = validateTimes(requestedStart, requestedEnd) ? requestedEnd - requestedStart : USE_MINUTES; return candidateStarts(date, duration).sort((a, b) => Math.abs(a.start - requestedStart) - Math.abs(b.start - requestedStart) || a.start - b.start).slice(0, limit);}
function lineCandidateText(items){return items.map((c, i) => `${['①','②','③','④','⑤'][i] || `${i + 1}.`}${jp(c.date)} ${rangeLabel(c.start, c.end)}`).join('\n');}
function buildLineReply(date, start, end, ok, candidates = []){if(ok) return `ご希望の${jp(date)} ${rangeLabel(start, end)}でご予約可能です。\nこちらのお時間でお取りしてもよろしいでしょうか？`; return `ご希望のお時間は埋まっております。\n近いお時間ですと、以下がご案内可能です。\n${lineCandidateText(candidates.slice(0, 3)) || 'ご案内可能な近い空き候補が見つかりませんでした。'}\nご都合の良いお時間はありますか？`;}
async function copyText(text){if(navigator.clipboard?.writeText) return navigator.clipboard.writeText(text); const area = document.createElement('textarea'); area.value = text; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove();}
function renderList(){const list = [...(yogaSnap.external_blocks || [])].sort((a,b) => (String(a.date) + String(a.start_minute).padStart(4,'0')).localeCompare(String(b.date) + String(b.start_minute).padStart(4,'0'))); $('#yogaList').innerHTML = list.length ? list.map(b => `<article class='res yoga-private'><h3>ヨガ個別予約：${esc(labelOrEmpty(b.member_name))}</h3><p>${esc(rangeText(b))}</p><p>インストラクター：${esc(labelOrEmpty(b.instructor_name))}</p><p>メモ：${esc(labelOrEmpty(b.note))}</p><button class='danger' data-yoga-delete='${esc(b.id)}'>削除</button></article>`).join('') : '<article class="res"><p>登録済みのヨガ個別予約はありません。</p></article>';}
function renderDailyCandidates(date){const all = candidateStarts(date, USE_MINUTES); const html = PERIODS.map(period => {const items = all.filter(c => period.ranges.some(([s, e]) => c.start >= s && c.start < e)).slice(0, DAILY_CANDIDATE_LIMIT); return `<section class="candidate-period"><h3>${period.label}</h3>${items.length ? `<div class="candidate-chips">${items.map(c => `<button type="button" class="candidate-chip" data-quick-date="${c.date}" data-quick-start="${fmtMin(c.start)}" data-quick-end="${fmtMin(c.end)}">${rangeLabel(c.start, c.end)}</button>`).join('')}</div>` : '<p class="small">表示できる空き候補はありません。</p>'}</section>`;}).join(''); $('#yogaOpenCandidates').innerHTML = `<h3>この日の空き候補</h3><p class="small">40分予約を10分単位で確認し、各時間帯ごとに最大${DAILY_CANDIDATE_LIMIT}件まで表示しています。</p><div class="daily-candidates">${html}</div>`;}
function renderUnavailable(){const date = selectedDateValue(); const list = unavailableBlocks(date); $('#yogaUnavailable').innerHTML = list.length ? `<div class="unavailable-list">${list.map(b => `<div class="unavailable-row"><strong>${rangeLabel(b.start_minute, b.end_minute)}</strong><span class="reason-label ${reasonClass(b.reason)}">${esc(b.reason)}</span></div>`).join('')}</div>` : '<p class="small">この日の予約不可時間はありません。</p>'; renderDailyCandidates(date);}
function renderQuickAvailability(){const date = quickDateValue(); const start = timeToMinute($('#quickStart')?.value); const end = timeToMinute($('#quickEnd')?.value); const result = availabilityFor(date, start, end); const candidates = result.ok ? [] : nearestCandidates(date, start, end, NEAR_CANDIDATE_LIMIT); const box = $('#quickAvailability'); if(!box) return; if(result.ok){box.className = 'quick-result available'; box.innerHTML = `<h3>予約できます</h3><p class="quick-time">${esc(jp(date))} ${rangeLabel(start, end)}</p><p>この内容で会員さんへ返信できます。</p><button type="button" id="quickUseForForm" class="btn">この内容で登録する</button>`;}else{box.className = 'quick-result unavailable'; box.innerHTML = `<h3>予約できません</h3><p class="quick-time">${validateTimes(start, end) ? `${esc(jp(date))} ${rangeLabel(start, end)}` : '選択内容を確認してください'}</p><p><strong>理由：</strong>${esc(result.reason)}</p><h4>近い空き候補</h4>${candidates.length ? `<div class="candidate-chips">${candidates.map(c => `<button type="button" class="candidate-chip" data-quick-date="${c.date}" data-quick-start="${fmtMin(c.start)}" data-quick-end="${fmtMin(c.end)}">${rangeLabel(c.start, c.end)}</button>`).join('')}</div>` : '<p>同じ日付で近い空き候補が見つかりませんでした。</p>'}`;}}
function syncQuickDateFromForm(){const date = selectedDateValue(); if($('#quickDate') && !$('#quickDate').value) $('#quickDate').value = date;}
function applyQuickToForm(){const form = $('#yogaForm'); if(!form) return; form.date.value = quickDateValue(); form.start.value = $('#quickStart').value; fillEndSelect(); form.end.value = $('#quickEnd').value; updateAvailability(); form.scrollIntoView({behavior: 'smooth', block: 'start'}); toast('登録フォームに反映しました');}
function updateAvailability(){fillEndSelect(); renderUnavailable(); syncQuickDateFromForm(); renderQuickAvailability(); const form = $('#yogaForm'); const btn = $('#yogaSubmit'); const start = timeToMinute(form.start.value); const end = timeToMinute(form.end.value); const result = availability(start, end); setMessage(result.reason, result.ok); if(btn) btn.disabled = !result.ok;}
async function loadYoga(){yogaSnap = await rpc('fs_yoga_private_snapshot', {p_admin_password: yogaPass}); renderList(); renderUnavailable(); updateAvailability();}
async function openYoga(){const input = $('#yogaPass').value || yogaPass; yogaPass = input; const date = $('#yogaForm input[name=date]'); if(date && !date.value) date.value = dk(new Date()); syncQuickDateFromForm(); await loadYoga(); sessionStorage.setItem('fs_yoga_private_pass', yogaPass); $('#loginView').classList.add('hidden'); $('#yogaView').classList.remove('hidden'); updateAvailability();}
$('#yogaOpen').addEventListener('click', () => openYoga().catch(err => {setMessage(err.message); alert(err.message);}));
$('#reloadYoga').addEventListener('click', () => loadYoga().then(() => toast('再読み込みしました')).catch(err => {setMessage(err.message); alert(err.message);}));
$('#logoutYoga').addEventListener('click', () => {sessionStorage.removeItem('fs_yoga_private_pass'); yogaPass = ''; $('#yogaPass').value = ''; $('#loginView').classList.remove('hidden'); $('#yogaView').classList.add('hidden');});
$('#yogaForm').addEventListener('change', e => {if(e.target?.name === 'start') fillEndSelect(); updateAvailability();});
$('#quickDate').addEventListener('change', renderQuickAvailability);
$('#quickStart').addEventListener('change', () => {fillEndSelectFor($('#quickStart'), $('#quickEnd')); renderQuickAvailability();});
$('#quickEnd').addEventListener('change', renderQuickAvailability);
$('#quickCopy').addEventListener('click', async () => {const date = quickDateValue(); const start = timeToMinute($('#quickStart').value); const end = timeToMinute($('#quickEnd').value); const result = availabilityFor(date, start, end); const candidates = result.ok ? [] : nearestCandidates(date, start, end, NEAR_CANDIDATE_LIMIT); try{await copyText(buildLineReply(date, start, end, result.ok, candidates)); $('#quickCopyStatus').textContent = 'コピーしました'; toast('コピーしました'); setTimeout(() => {$('#quickCopyStatus').textContent = '';}, 2500);}catch(err){$('#quickCopyStatus').textContent = 'コピーできませんでした'; alert(err.message);}});
$('#yogaForm').addEventListener('submit', async e => {e.preventDefault(); const form = e.currentTarget; if(!(form instanceof HTMLFormElement)) return; const fd = new FormData(form); const start = timeToMinute(fd.get('start')); const end = timeToMinute(fd.get('end')); const result = availability(start, end); if(!result.ok){setMessage(result.reason); alert(result.reason); return;} try{await rpc('fs_yoga_private_create', {p_admin_password: yogaPass, p_date: fd.get('date'), p_start_minute: start, p_end_minute: end, p_member_name: String(fd.get('memberName') || '').trim(), p_instructor_name: String(fd.get('instructorName') || '').trim(), p_note: String(fd.get('note') || '').trim()}); await loadYoga(); form.reset(); form.date.value = dk(new Date()); fillStartSelect(); fillEndSelect(); updateAvailability(); toast('ヨガ個別予約を登録しました');}catch(err){setMessage(err.message); alert(err.message);}});
document.addEventListener('click', e => {const useBtn = e.target.closest('#quickUseForForm'); if(useBtn){applyQuickToForm(); return;} const candidate = e.target.closest('[data-quick-start][data-quick-end]'); if(candidate){if(candidate.dataset.quickDate) $('#quickDate').value = candidate.dataset.quickDate; $('#quickStart').value = candidate.dataset.quickStart; fillEndSelectFor($('#quickStart'), $('#quickEnd')); $('#quickEnd').value = candidate.dataset.quickEnd; renderQuickAvailability(); return;} const btn = e.target.closest('[data-yoga-delete]'); if(!btn) return; if(!confirm('このヨガ個別予約を削除しますか？')) return; rpc('fs_yoga_private_delete', {p_admin_password: yogaPass, p_external_block_id: btn.dataset.yogaDelete}).then(() => loadYoga()).then(() => toast('ヨガ個別予約を削除しました')).catch(err => {setMessage(err.message); alert(err.message);});});
window.addEventListener('DOMContentLoaded', () => {fillStartSelect(); fillEndSelect(); fillQuickSelects(); $('#yogaPass').value = yogaPass; const date = $('#yogaForm input[name=date]'); if(date) date.value = dk(new Date()); if($('#quickDate')) $('#quickDate').value = selectedDateValue(); updateAvailability(); if(yogaPass) openYoga().catch(() => {});});
