const yogaDb = window.supabase.createClient(window.FRIENDS_SUPABASE_URL, window.FRIENDS_SUPABASE_ANON_KEY);
let yogaPass = sessionStorage.getItem('fs_yoga_private_pass') || '';
let yogaSnap = {reservations: [], closed_slots: [], external_blocks: []};
const USE_MINUTES = 40;
const BLOCK_MINUTES = 50;
const TEN_MINUTES = 10;
const HOLIDAYS = ['2026-01-01','2026-01-12','2026-02-11','2026-02-23','2026-03-20','2026-04-29','2026-05-03','2026-05-04','2026-05-05','2026-05-06','2026-07-20','2026-08-11','2026-09-21','2026-09-22','2026-09-23','2026-10-12','2026-11-03','2026-11-23'];
const $ = q => document.querySelector(q);
const pad = n => String(n).padStart(2, '0');
const dk = d => d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate());
const fmtMin = m => {m = Number(m); return m === 1440 ? '24:00' : pad(Math.floor(m / 60)) + ':' + pad(m % 60);};
const jp = s => {const d = new Date(s + 'T00:00:00'); return `${d.getMonth() + 1}/${d.getDate()}（${'日月火水木金土'[d.getDay()]}）`;};
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;'}[m]));
function toast(msg){const el = $('#toast'); el.textContent = msg; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2500);}
function setMessage(msg, ok = false){const el = $('#yogaStatus'); if(!el) return; el.textContent = msg || ''; el.className = msg ? `notice ${ok ? 'ok' : 'danger'}` : 'notice';}
async function rpc(name, args){const {data, error} = await yogaDb.rpc(name, args); if(error) throw new Error(error.message); if(!data?.ok) throw new Error(data?.error || 'RPC失敗'); return data;}
function timeToMinute(value){if(value === '24:00') return 1440; const [h, m] = String(value || '').split(':').map(Number); if(!Number.isFinite(h) || !Number.isFinite(m)) return NaN; return h * 60 + m;}
function validTenMinute(minute){return Number.isInteger(minute) && minute >= 0 && minute <= 1440 && minute % TEN_MINUTES === 0;}
function validateTimes(start, end){return validTenMinute(start) && validTenMinute(end) && start < end && start <= 1430 && end >= 10 && end <= 1440;}
function overlapsRange(aStart, aEnd, bStart, bEnd){return Number(aStart) < Number(bEnd) && Number(bStart) < Number(aEnd);}
function blockEnd(minute){return Number(minute) + BLOCK_MINUTES;}
function rangeText(block){return `${jp(block.date)} ${fmtMin(block.start_minute)}〜${fmtMin(block.end_minute)}`;}
function labelOrEmpty(value){const text = String(value || '').trim(); return text || '未入力';}
function selectedDateValue(){return $('#yogaForm input[name=date]')?.value || dk(new Date());}
function fixedBlocks(date){const day = new Date(date + 'T00:00:00').getDay(); if(HOLIDAYS.includes(date)) return [[510,820,'通常ヨガ・セミパーソナル']]; if(day === 1) return [[510,610,'通常ヨガ'],[1080,1330,'セミパーソナル']]; if(day === 2) return [[510,610,'通常ヨガ'],[720,820,'セミパーソナル'],[1080,1330,'セミパーソナル']]; if(day === 3) return [[1080,1330,'セミパーソナル']]; if(day === 4) return [[690,790,'通常ヨガ'],[1215,1315,'セミパーソナル']]; if(day === 5) return [[1080,1330,'セミパーソナル']]; if(day === 6 || day === 0) return [[460,820,'通常ヨガ・セミパーソナル']]; return [];}
function unavailableBlocks(date){const reservations = (yogaSnap.reservations || []).filter(r => r.date === date).map(r => ({start_minute: Number(r.start_minute), end_minute: blockEnd(r.start_minute), reason: 'セルフジム予約'}));
  const closed = (yogaSnap.closed_slots || []).filter(c => c.date === date).map(c => ({start_minute: Number(c.start_minute), end_minute: blockEnd(c.start_minute), reason: c.reason ? `利用不可枠（${c.reason}）` : '利用不可枠'}));
  const yoga = (yogaSnap.external_blocks || []).filter(b => b.date === date).map(b => ({start_minute: Number(b.start_minute), end_minute: Number(b.end_minute), reason: '既存のヨガ個別予約'}));
  const fixed = fixedBlocks(date).map(([s, e, reason]) => ({start_minute: s, end_minute: e, reason}));
  return [...reservations, ...closed, ...yoga, ...fixed].sort((a, b) => a.start_minute - b.start_minute || a.end_minute - b.end_minute);
}
function availability(start, end){if(!validateTimes(start, end)) return {ok: false, reason: '開始・終了時間は10分単位で、終了を開始より後にしてください。'}; const hit = unavailableBlocks(selectedDateValue()).find(b => overlapsRange(start, end, b.start_minute, b.end_minute)); if(hit) return {ok: false, reason: `この時間は${hit.reason}と重なっています`}; return {ok: true, reason: 'この時間は予約できます'};}
function timeOptions(start = 0, end = 1430){let html = ''; for(let m = start; m <= end; m += TEN_MINUTES) html += `<option value='${fmtMin(m)}'>${fmtMin(m)}</option>`; return html;}
function fillStartSelect(){const start = $('#yogaStart'); if(!start) return; const current = start.value || '08:10'; start.innerHTML = timeOptions(0, 1430); start.value = current; if(!start.value) start.value = '08:10';}
function fillEndSelect(){const form = $('#yogaForm'); const end = $('#yogaEnd'); if(!form || !end) return; const startMinute = timeToMinute(form.start.value); const current = end.value; const minEnd = validTenMinute(startMinute) ? startMinute + TEN_MINUTES : TEN_MINUTES; end.innerHTML = timeOptions(minEnd, 1440); if(current && timeToMinute(current) > startMinute) end.value = current; if(!end.value) end.value = fmtMin(Math.min(1440, startMinute + USE_MINUTES));}
function renderList(){const list = [...(yogaSnap.external_blocks || [])].sort((a,b) => (String(a.date) + String(a.start_minute).padStart(4,'0')).localeCompare(String(b.date) + String(b.start_minute).padStart(4,'0'))); $('#yogaList').innerHTML = list.length ? list.map(b => `<article class='res yoga-private'><h3>ヨガ個別予約：${esc(labelOrEmpty(b.member_name))}</h3><p>${esc(rangeText(b))}</p><p>インストラクター：${esc(labelOrEmpty(b.instructor_name))}</p><p>メモ：${esc(labelOrEmpty(b.note))}</p><button class='danger' data-yoga-delete='${esc(b.id)}'>削除</button></article>`).join('') : '<article class="res"><p>登録済みのヨガ個別予約はありません。</p></article>';}
function renderUnavailable(){const date = selectedDateValue(); const list = unavailableBlocks(date); const openCount = Array.from({length: 144}, (_, i) => i * TEN_MINUTES).filter(start => availability(start, Math.min(1440, start + USE_MINUTES)).ok).length; $('#yogaUnavailable').innerHTML = list.length ? `<ul>${list.map(b => `<li><strong>${fmtMin(b.start_minute)}〜${fmtMin(b.end_minute)}</strong>　${esc(b.reason)}</li>`).join('')}</ul>` : '<p class="small">この日の予約不可時間はありません。</p>'; $('#yogaOpenCandidates').textContent = `40分予約の候補目安：${openCount}件（10分単位の開始候補）`;}
function updateAvailability(){fillEndSelect(); renderUnavailable(); const form = $('#yogaForm'); const btn = $('#yogaSubmit'); const start = timeToMinute(form.start.value); const end = timeToMinute(form.end.value); const result = availability(start, end); setMessage(result.reason, result.ok); if(btn) btn.disabled = !result.ok;}
async function loadYoga(){yogaSnap = await rpc('fs_yoga_private_snapshot', {p_admin_password: yogaPass}); renderList(); renderUnavailable(); updateAvailability();}
async function openYoga(){const input = $('#yogaPass').value || yogaPass; yogaPass = input; await loadYoga(); sessionStorage.setItem('fs_yoga_private_pass', yogaPass); $('#loginView').classList.add('hidden'); $('#yogaView').classList.remove('hidden'); const date = $('#yogaForm input[name=date]'); if(date && !date.value) date.value = dk(new Date()); updateAvailability();}
$('#yogaOpen').addEventListener('click', () => openYoga().catch(err => {setMessage(err.message); alert(err.message);}));
$('#reloadYoga').addEventListener('click', () => loadYoga().then(() => toast('再読み込みしました')).catch(err => {setMessage(err.message); alert(err.message);}));
$('#logoutYoga').addEventListener('click', () => {sessionStorage.removeItem('fs_yoga_private_pass'); yogaPass = ''; $('#yogaPass').value = ''; $('#loginView').classList.remove('hidden'); $('#yogaView').classList.add('hidden');});
$('#yogaForm').addEventListener('change', e => {if(e.target?.name === 'start') fillEndSelect(); updateAvailability();});
$('#yogaForm').addEventListener('submit', async e => {e.preventDefault(); const form = e.currentTarget; if(!(form instanceof HTMLFormElement)) return; const fd = new FormData(form); const start = timeToMinute(fd.get('start')); const end = timeToMinute(fd.get('end')); const result = availability(start, end); if(!result.ok){setMessage(result.reason); alert(result.reason); return;} try{await rpc('fs_yoga_private_create', {p_admin_password: yogaPass, p_date: fd.get('date'), p_start_minute: start, p_end_minute: end, p_member_name: String(fd.get('memberName') || '').trim(), p_instructor_name: String(fd.get('instructorName') || '').trim(), p_note: String(fd.get('note') || '').trim()}); await loadYoga(); form.reset(); form.date.value = dk(new Date()); fillStartSelect(); fillEndSelect(); updateAvailability(); toast('ヨガ個別予約を登録しました');}catch(err){setMessage(err.message); alert(err.message);}});
document.addEventListener('click', e => {const btn = e.target.closest('[data-yoga-delete]'); if(!btn) return; if(!confirm('このヨガ個別予約を削除しますか？')) return; rpc('fs_yoga_private_delete', {p_admin_password: yogaPass, p_external_block_id: btn.dataset.yogaDelete}).then(() => loadYoga()).then(() => toast('ヨガ個別予約を削除しました')).catch(err => {setMessage(err.message); alert(err.message);});});
window.addEventListener('DOMContentLoaded', () => {fillStartSelect(); fillEndSelect(); $('#yogaPass').value = yogaPass; const date = $('#yogaForm input[name=date]'); if(date) date.value = dk(new Date()); updateAvailability(); if(yogaPass) openYoga().catch(() => {});});
